Controllers/ForDirectorController.cs
using eDnevnik.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace eDnevnik.Controllers
{
    public class ForDirectorController : Controller
    {
        DnevnikEntities db = new DnevnikEntities();
        // GET: ForDirector
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MainPage()
        {
            return View();
        }

        public JsonResult getClass(string level, string letter)
        {
            int lvl = Int32.Parse(level);
            if (Request.IsAjaxRequest())
            {    
                
                var managers = (from m in db.Pupils
                               join c in db.Classes on m.Class equals c.Id
                               where c.Level == lvl && c.Name == letter
                               orderby c.Name
                               select new { m.Id, m.LastName, m.FirstName, m.Phone, m.Parent }).ToList();
                var count = managers.Count();

                var array = new { managers, count };

                return new JsonResult { Data = array, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }

            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult EditFirstTime(int id)
        {
            DnevnikEntities _db = new DnevnikEntities();
            string directorName = HttpContext.User.Identity.Name;
            int directorId = _db.Directors.Where(p => (p.Email.Equals(directorName)) || (p.UserName.Equals(directorName))).FirstOrDefault().Id;
            if (id == directorId)
            {
                Director d = _db.Directors.Find(id);
                return View(d);
            }


            
            return View();
        }

        [HttpPost]
        public ActionResult EditFirstTime(HttpPostedFileBase ImageFile, Director d, string pass, string passConf)
        {
            if (ModelState.IsValid)
            {               
                if (pass == passConf)
                {
                    if (ImageFile != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                        string fileExtension = Path.GetExtension(ImageFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + fileExtension;
                        d.ImagePath = "~/image/directorPhoto/" + fileName;
                        fileName = Path.Combine(Server.MapPath("~/image/directorPhoto/"), fileName);
                        ImageFile.SaveAs(fileName);
                    }
                    var db = new DnevnikEntities();
                    db.Directors.Attach(d);
                    d.Password = Crypto.HashPassword(pass);
                    db.Entry(d).Property(p => p.Password).IsModified = true;
                    db.Entry(d).Property(p => p.LastName).IsModified = true;
                    db.Entry(d).Property(p => p.FirstName).IsModified = true;
                    db.Entry(d).Property(p => p.DoB).IsModified = true;
                    db.Entry(d).Property(p => p.Address).IsModified = true;
                    db.Entry(d).Property(p => p.Phone).IsModified = true;
                    db.Entry(d).Property(p => p.Email).IsModified = true;
                    db.Entry(d).Property(p => p.ImagePath).IsModified = true;
                    db.SaveChanges();

                    return RedirectToAction("Index", new { id = d.Id });
                }
                else
                {
                    ViewBag.Pass = "Пароли не совпадают";
                    return View();
                }
            }
            return View();

        }

        public ActionResult TimeTableManagement()
        {
            return View();
        }

        public JsonResult getTeachers(string subjectId)
        {
            int id = Int32.Parse(subjectId);
            if (Request.IsAjaxRequest())
            {
                if (id == -1)
                {
                    var managers = db.Teachers.OrderBy(m => m.LastName).Select(m => new { m.LastName, m.FirstName, m.Phone, m.Email, m.Id }).ToList();

                    return new JsonResult { Data = managers, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                }
                else
                {
                    var managers = (from t in db.Teachers
                                    join tsa in db.SubjectTeacherAllocations on t.Id equals tsa.Teacher
                                    join s in db.Subjects on tsa.Subject equals s.Id
                                    where s.Id == id
                                    orderby t.LastName
                                    select new { t.LastName, t.FirstName, t.Id }).ToList();

                    return new JsonResult { Data = managers, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

                }
            }

            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult getClasses(string level)
        {
            if (Request.IsAjaxRequest())
            {
                int? classlevel = int.Parse(level);
                if (classlevel == null || classlevel == 0)
                {
                    var classes = db.Classes.Select(c => new { c.Id, c.Level, c.Name }).ToList();
                    return new JsonResult { Data = classes, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                }
                else
                {
                    var classes = db.Classes.Where(c => c.Level == classlevel).Select(c => new { c.Id, c.Level, c.Name }).ToList();
                    return new JsonResult { Data = classes, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                }
            }
            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        public JsonResult getSubjects()
        {
            
            if (Request.IsAjaxRequest())
            {
               
                    var managers = db.Subjects.OrderBy(m => m.Level).Select(m => new { m.SubjectName, m.Level, m.Id }).ToList();

                    return new JsonResult { Data = managers, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
               
            }

            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult getSubjectsByTeacher(string id, string level)
        {
            int teacherId = Int32.Parse(id);
            if (Request.IsAjaxRequest())
            {
                int? classlevel = int.Parse(level);
                
                if(classlevel == null || classlevel == 0)
                {
                    var managers = (from s in db.Subjects
                                    join sa in db.SubjectTeacherAllocations on s.Id equals sa.Subject                                    
                                    where sa.Teacher == teacherId
                                    select new { s.Id, s.Level, s.SubjectName }).ToList();
                    return new JsonResult { Data = managers, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

                }
                else
                {
                   var managers = SubjectList(teacherId).Where(s => s.Level == classlevel).Select(s => new { s.Id, s.Level, s.SubjectName});
                    return new JsonResult { Data = managers, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                };

                

            }

            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult getTeacherTimeTable(string id, string subjOrd, string day)
        {
            int teacherId;
            int ord;
            int dayNum;
            teacherId = Int32.Parse(id);
            ord = Int32.Parse(subjOrd);
            dayNum = Int32.Parse(day);
            if (Request.IsAjaxRequest())
            {

                var timetable = ifExists(teacherId, dayNum, ord);
                if (timetable != null)
                {
                    var subject = db.Subjects.Where(s => s.Id == timetable.Subject).FirstOrDefault().SubjectName;
                    var classLevel = db.Classes.Where(c => c.Id == timetable.Class).FirstOrDefault().Level;
                    var classLetter = db.Classes.Where(c => c.Id == timetable.Class).FirstOrDefault().Name;
                    var data = new { subject, classLevel, classLetter };
                    return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                }
                else
                {
                    var subject = "--";
                    var classLevel = "-";
                    var classLetter = "-";
                    var data = new { subject, classLevel, classLetter };
                    return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

                }

            }

            return new JsonResult
            {
                Data = "error",

Views/ForDirector/EditFirstTime.cshtml
@model eDnevnik.Director

@{
    ViewBag.Title = "EditFirstTime";
}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jquery3")
@Scripts.Render("~/bundles/jqueryUi")
@Styles.Render("~/bundles/jqueryUiCss")
<script type="text/javascript">


    $(document).ready(function () {
        $(".directorInputField.pass").val("");
        $(".directorInputField.passConfirm").val("");
    });
        </script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="formFirstEdit">
        <h1>Пожалуйста Заполните Анкету</h1>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            @Html.Label("Пароль*", htmlAttributes: new { @class = "directorInputLabel" })

                @Html.Editor("pass", new { htmlAttributes = new { @class = "directorInputField pass" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

        @Html.Label("Подтвердите Пароль*", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.Editor("passConf", new { htmlAttributes = new { @class = "directorInputField passConfirm" } })
        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })



            @Html.Label("Фамилия*", htmlAttributes: new { @class = "directorInputLabel" })

                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "directorInputField" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })



            @Html.Label("Имя*", htmlAttributes: new { @class = "directorInputLabel" })

                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "directorInputField" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })



            @Html.Label("Дата Рождения", htmlAttributes: new { @class = "directorInputLabel" })

                @Html.EditorFor(model => model.DoB, new { htmlAttributes = new { @class = "directorInputField datepicker" } })
                @Html.ValidationMessageFor(model => model.DoB, "", new { @class = "text-danger" })



            @Html.Label("Адрес*", htmlAttributes: new { @class = "directorInputLabel" })

                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "directorInputField" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })


            @Html.Label("Тел*", htmlAttributes: new { @class = "directorInputLabel" })

                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "directorInputField" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })



            @Html.Label("email*", htmlAttributes: new { @class = "directorInputLabel" })

                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "directorInputField" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })



            @Html.Label("Загрузите Фото:", htmlAttributes: new { @class = "directorInputLabel" })

                <input type="file" name="ImageFile" id="teacherPhoto" />






                <input type="submit" value="Сохранить" class="directorInputField" />

        </div>

}


Views/ForDirector/Index.cshtml

@{
    ViewBag.Title = "Index";
}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jquery3")
@Scripts.Render("~/bundles/jqueryUi")
@Styles.Render("~/bundles/jqueryUiCss")
<script type="text/javascript">
    $(document).ready(function () {
        getClasses();
        function getClasses() {
            $(".dirContent").empty();
            $(".dirContent").append("<div class='classFilterBox'></div>");
            $(".classFilterBox").append("<div class='classFilterTitle'>Управление Классами</div>");
            $(".classFilterBox").append("<div class='classFilterLevel'>" +
                "<a href='#' class='classFilterActive'>1</a>" +
                "<a href='#'>2</a>" +
                "<a href='#'>3</a>" +
                "<a href='#'>4</a>" +
                "<a href='#'>5</a>" +
                "<a href='#'>6</a>" +
                "<a href='#'>7</a>" +
                "<a href='#'>8</a>" +
                "<a href='#'>9</a>" +
                "<a href='#'>10</a>" +
                "<a href='#'>11</a>" +
                "</div>");
            $(".classFilterBox").append("<div class='classFilterLetter'>" +
                "<a href='#' class='classFilterActive'>А</a>" +
                "<a href='#'>Б</a>" +
                "<a href='#'>В</a>" +
                "<a href='#'>Г</a>" +
                "<a href='#'>Д</a>" +
                "<a href='#'>Е</a>" +
                "<a href='#'>Ж</a>" +                
                "</div>");
            var level = $(".classFilterLevel a.classFilterActive").html();
            var letter = $(".classFilterLetter a.classFilterActive").html();
            getClassesAjax(level, letter);
            $(".classFilterLevel a").click(function () {
                $(".classFilterLevel a").removeClass("classFilterActive");
                $(this).addClass("classFilterActive");
                var level = $(".classFilterLevel a.classFilterActive").html();
                var letter = $(".classFilterLetter a.classFilterActive").html();
                getClassesAjax(level, letter);
            });
            $(".classFilterLetter a").click(function () {
                $(".classFilterLetter a").removeClass("classFilterActive");
                $(this).addClass("classFilterActive");
                var level = $(".classFilterLevel a.classFilterActive").html();
                var letter = $(".classFilterLetter a.classFilterActive").html();
                getClassesAjax(level, letter);
            });           
        };

        function getClassesAjax(x, y) {
            $(".classContainer").remove();
            $(".dirContent").append("<div class='classContainer'></div>");
            $(".classContainer").append("<div class='tableDirClass'><h2><div><b>" + x + " " + y + "</b></div></h2><div>");
            $(".tableDirClass").append("<table id='forDirectorTable'><tr><th>№</th><th>Фамилия</th><th>Имя</th><th>Родитель</th><th>Тел.</th><th>ID</th><th>Управление</th></tr></table>" +
              "<div id='endAdminTable'></div>");
            $.ajax({
                url: '@Url.Action("getClass", "ForDirector")',
                method: 'post',
                data: JSON.stringify({
                    "level": x,
                    "letter": y
                }),
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $(".tableDirClass h2").append("<div> Коль-во учащихся: " + data.count + "</div> <a href='#'><img class='tableDirTimetableEditButtion' src='/image/icons/timeTableEdit.png' alt='Расписание' />" +
                        "<div class='tableDirTimetableEditButtionDesc'>Изменить Расписание</div>" +
                        "<img class='tableDirHeadTeacherEditButtion'src='/image/icons/headTeacher.png' alt='КлассРук' />"+
                     "<div class='tableDirHeadTeacherEditButtionDesc'>Изменить Классного Руководителя</div></a>");
                    $(".tableDirTimetableEditButtion").mouseenter(function () {
                        $(this).addClass("hover");
                        $(".tableDirTimetableEditButtionDesc").stop().fadeIn('slow');
                    });
                    $(".tableDirTimetableEditButtion").mouseleave(function () {
                        $(this).removeClass("hover");
                        $(".tableDirTimetableEditButtionDesc").stop().fadeOut('slow');
                    });
                    $(".tableDirHeadTeacherEditButtion").mouseenter(function () {
                        $(this).addClass("hover");
                        $(".tableDirHeadTeacherEditButtionDesc").stop().fadeIn('slow');
                    });
                    $(".tableDirHeadTeacherEditButtion").mouseleave(function () {
                        $(this).removeClass("hover");
                        $(".tableDirHeadTeacherEditButtionDesc").stop().fadeOut('slow');
                    });
                    $i = 0;
                    $(data.managers).each(function (index, item) {
                        $i++;
                        $(".tableDirClass table").append("<tr><td>" + $i + "</td><td class='lastNameTd'>" + item.LastName + "</td><td class='firstNameTd'>" +
                            item.FirstName + "</td>" +
                            "<td class='phoneTd'>" + item.Parent + "</td>" +
                            "<td class='emailTd'>" + item.Phone + "</td>" +
                            "<td class='idTd'>" + item.Id + "</td>" +
                            "<td><a href='#' class='managerDetails'><img src='/image/icons/details.png' alt='Детали' /></a>" +
                            "<a href='#' class='managerEdit'><img src='/image/icons/edit.png' alt='Редактировать' /></a>" +                            
                            "</td></tr>");
                    });
                },

                error: function () {
                    alert('ee');
                }
            });
        };

        $("#grpd").click(function () {
            getClasses();
        });

    });

    </script>

<div id="topLineLogin">
    <div class="adminSchoolName">
        <img src="~/image/icons/lenta/lenta.png" />
        <p>Школа №000</p>
    </div>
    <div class="userButtonPack">
        @*<a href="#"><div class="userBtnDescription" id="">Управление<br /> Предметами</div><img id="sbjd" src="~/image/icons/textbooks.png" alt="Управление Предметами" /></a>
        <a href="#"><div id="">Управление<br /> Учениками</div><img id="ppld" src="~/image/icons/pupil.png" alt="Управление Учениками" /></a>
        <a href="#"><div id="">Управление<br /> Родителями</div><img id="prtd" src="~/image/icons/parent_icon.png" alt="Управление Родителями" /></a>
        <a href="#"><div id="">Управление<br /> Учителями</div><img id="tcrd" src="~/image/icons/teacher.png" alt="Управление учителями школы" /></a>
        <a href="#"><div id="">Управление<br /> Менеджером</div><img id="mnrd" src="~/image/icons/Manager-512.png" alt="Управление менеджером школы" /></a>*@
        <a href="@Url.Action("TimeTableManagement")"><div class="userBtnDescription" id="">Управление<br /> Группами</div><img id="tmtbl" src="~/image/icons/timeTableEdit.png" alt="Управление Группами" /></a>
        <a href="#"><div class="userBtnDescription" id="">Управление<br /> Группами</div><img id="grpd" src="~/image/icons/group.png" alt="Управление Группами" /></a>
        
    </div>
</div>

<div class="dirContent">

</div>

Views/ForDirector/MainPage.cshtml

@{
    ViewBag.Title = "MainPage";
}


