Controllers/ForParentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace eDnevnik.Controllers
{
    
    public class ForParentController : Controller
    {
        // GET: ForParent
        public ActionResult Index(int id)
        {
            DnevnikEntities _db = new DnevnikEntities();
            string directorName = HttpContext.User.Identity.Name;
            int directorId = _db.Parents.Where(p => (p.Email.Equals(directorName)) || (p.UserName.Equals(directorName))).FirstOrDefault().Id;
            if (id == directorId)
            {
                ViewBag.Id = directorId;
                Parent d = _db.Parents.Find(id);
                return View(d);
            }



            return View();
        }

        public ActionResult EditFirstTime(int id)
        {
            DnevnikEntities _db = new DnevnikEntities();
            string directorName = HttpContext.User.Identity.Name;
            int directorId = _db.Parents.Where(p => (p.Email.Equals(directorName)) || (p.UserName.Equals(directorName))).FirstOrDefault().Id;
            if (id == directorId)
            {
                Parent d = _db.Parents.Find(id);
                return View(d);
            }



            return View();
        }

        [HttpPost]
        public ActionResult EditFirstTime(HttpPostedFileBase ImageFile, Parent d, string pass, string passConf)
        {
            if (ModelState.IsValid)
            {
                if (pass == passConf)
                {
                    if (ImageFile != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                        string fileExtension = Path.GetExtension(ImageFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + fileExtension;
                        d.ImagePath = "~/image/teacherPhoto/" + fileName;
                        fileName = Path.Combine(Server.MapPath("~/image/teacherPhoto/"), fileName);
                        ImageFile.SaveAs(fileName);
                    }
                    var db = new DnevnikEntities();
                    db.Parents.Attach(d);
                    d.Password = Crypto.HashPassword(pass);
                    db.Entry(d).Property(p => p.Password).IsModified = true;
                    db.Entry(d).Property(p => p.LastName).IsModified = true;
                    db.Entry(d).Property(p => p.FirstName).IsModified = true;
                    db.Entry(d).Property(p => p.DoB).IsModified = true;
                    db.Entry(d).Property(p => p.Address).IsModified = true;
                    db.Entry(d).Property(p => p.Phone).IsModified = true;
                    db.Entry(d).Property(p => p.Email).IsModified = true;
                    db.Entry(d).Property(p => p.ImagePath).IsModified = true;
                    db.SaveChanges();

                    return RedirectToAction("Index", new { id = d.Id });
                }
                else
                {
                    ViewBag.Pass = "Пароли не совпадают";
                    return View();
                }
            }
            return View();

        }

        public JsonResult getMyChildren(string id)
        {
            int PID = Int32.Parse(id);
            if (Request.IsAjaxRequest())
            {


                DnevnikEntities db = new DnevnikEntities();
                var children = db.Pupils.Where(p => p.Parent == PID).Select(p => new { p.Id, p.LastName, p.FirstName, p.Class }).ToList();
                return new JsonResult { Data = children, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

               
            }

            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult getClassName(string id)
        {
            int PID = Int32.Parse(id);
            if (Request.IsAjaxRequest())
            {


                DnevnikEntities db = new DnevnikEntities();
                var classes = db.Classes.Where(p => p.Id == PID).Select(p => new { p.Id, p.Level, p.Name }).FirstOrDefault();
                return new JsonResult { Data = classes, JsonRequestBehavior = JsonRequestBehavior.AllowGet };


            }

            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult getDiaries(string id, string ddate)
        {
            DateTime d = DateTime.Parse(ddate);
            int SID = Int32.Parse(id);
            if (Request.IsAjaxRequest())
            {


                DnevnikEntities db = new DnevnikEntities();
                var diaries = db.Diaries.Where(p => p.Pupil == SID && p.DateOfIssue == d ).Select(p => new { p.DiaryId, p.Attandance, p.DateOfIssue, p.Details, p.Homework, p.Mark, p.Subject }).ToList();
                return new JsonResult { Data = diaries, JsonRequestBehavior = JsonRequestBehavior.AllowGet };


            }

            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult getSubjectName(string id)
        {
            
            int SID = Int32.Parse(id);
            if (Request.IsAjaxRequest())
            {


                DnevnikEntities db = new DnevnikEntities();
                var subjects = db.Subjects.Where(p => p.Id == SID ).Select(p => new { p.SubjectName }).FirstOrDefault();
                return new JsonResult { Data = subjects, JsonRequestBehavior = JsonRequestBehavior.AllowGet };


            }

            return new JsonResult
            {
                Data = "error",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

    }
}

Views/ForParent/EditFirstTime.cshtml
@model eDnevnik.Parent

@{
    ViewBag.Title = "EditFirstTime";
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jquery3")
@Scripts.Render("~/bundles/jqueryUi")
@Styles.Render("~/bundles/jqueryUiCss")
<script type="text/javascript">


    $(document).ready(function () {
        $(".directorInputField.pass").val("");
        $(".directorInputField.passConfirm").val("");
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="formFirstEdit">
        <h1>Пожалуйста Заполните Анкету</h1>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        @Html.Label("Пароль*", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.Editor("pass", new { htmlAttributes = new { @class = "directorInputField pass" } })
        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

        @Html.Label("Подтвердите Пароль*", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.Editor("passConf", new { htmlAttributes = new { @class = "directorInputField passConfirm" } })
        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })



        @Html.Label("Фамилия*", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "directorInputField" } })
        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })



        @Html.Label("Имя*", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "directorInputField" } })
        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })



        @Html.Label("Дата Рождения", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.EditorFor(model => model.DoB, new { htmlAttributes = new { @class = "directorInputField datepicker" } })
        @Html.ValidationMessageFor(model => model.DoB, "", new { @class = "text-danger" })



        @Html.Label("Адрес*", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "directorInputField" } })
        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })


        @Html.Label("Тел*", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "directorInputField" } })
        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })



        @Html.Label("email*", htmlAttributes: new { @class = "directorInputLabel" })

        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "directorInputField" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })



        @Html.Label("Загрузите Фото:", htmlAttributes: new { @class = "directorInputLabel" })

        <input type="file" name="ImageFile" id="teacherPhoto" />






        <input type="submit" value="Сохранить" class="directorInputField" />

    </div>

}


Views/ForParent/Index.cshtml

@{
    ViewBag.Title = "Index";
}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jquery3")
@Styles.Render("~/bundles/jqueryUiCss")

<script type="text/javascript">
    function getDiaries(){
        var SID = $(".parentControlPack div.active span.id").html();
        var ddtae = $("input[type=date]").val();
        $.ajax({
            url: '@Url.Action("getDiaries", "ForParent")',
            method: 'post',
            data: JSON.stringify({
                "id": SID,
                "ddate" : ddtae 
            }),
            dataType: 'json',
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                $("#adminContent").empty();
                $("#adminContent").append("<div class='tableHead'><h2>Дневник Учащегося</h2></div>");

                $("#adminContent").append($("<div id='manTable' class='forTeacher'><table><tr><th>№</th><th class='idTd'>ID</th><th>Предмет</th><th>Домашнее Задание</th><th>Комментарий</th><th>Оценка</th></tr></table>" +
                   "<div id='endAdminTable'></div></div>"));
                $i = 0;
                $(data).each(function (index, item) {
                    $i++;
                    $("#adminContent table").append($("<tr><td>" + $i + "</td>"+
                        "<td class='idTd'>" + item.DiaryId + "</td>" +  
                        "<td class='subjectTd'>" + item.Subject + "</td>"+ 
                        "<td class='homeTaskTd'>" + item.Homework + "</td>" +
                        "<td class='detailsTd'>" + item.Details +"</td>" + 
                        "<td class='markTd'>" + item.Mark +"</td></tr>"));
                });
                $("#adminContent table tr").each(function(){
                    if($(this).children().first().html() != "№"){
                        var ID = $(this).children().first().next().next().html(); 
                        var subject = $(this).children().first().next().next(); 
                        $.ajax({
                            url: '@Url.Action("getSubjectName", "ForParent")',
                            method: 'post',
                            data: JSON.stringify({
                                "id": ID,
                                        
                            }),
                            dataType: 'json',
                            contentType: "application/json; charset=utf-8",
                            success: function (data) {
                                subject.empty();
                                subject.html(data.SubjectName);
                            }
                        });
                    };
                });
            }
        });
    };
    $(document).ready(function () {
        var ID = @ViewBag.Id;
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth() + 1;
        if (dd < 10) { dd = '0' + dd };
        if (mm < 10) { mm = "0" + mm };
        var yyyy = today.getFullYear();
        today = yyyy + "-" + mm + "-" + dd;
        $("input[type=date]").val(today);
        
        $.ajax({
            url: '@Url.Action("getMyChildren", "ForParent")',
            method: 'post',
            data: JSON.stringify({
                "id": ID                
            }),
            dataType: 'json',
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                $(".parentControlPack").empty();
                $(data).each(function(index, i){
                    $(".parentControlPack").append("<div><span class='id'>"+i.Id+
                        "</span>"+i.LastName + " " + i.FirstName + " <span class='classId'>"+
                        i.Class + "</span></div>");
                });
                $(".parentControlPack").children().first().addClass("active");
                $(".parentControlPack div").each(function(){
                    var classID = $(this).find("span.classId").html();
                    var block = $(this);                   
                    $.ajax({
                        url: '@Url.Action("getClassName", "ForParent")',
                        method: 'post',
                        data: JSON.stringify({
                            "id": classID                
                        }),
                        dataType: 'json',
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            block.children("span.classId").empty();
                            block.children("span.classId").append(data.Level+data.Name);
                        }
                    });
               
                });

                $(".parentControlPack div").click(function(){
                    $(".parentControlPack div").removeClass("active");
                    $(this).addClass("active");
                    getDiaries();
                });

                $("input[type=date]").change(function(){                    
                    getDiaries();
                });

                
                
            }
        });
    });
</script>


<div id="topLineLogin">
    <div class="adminSchoolName">
        <img src="~/image/icons/lenta/lenta.png" />
        <p>Школа №000</p>
    </div>
    <div class="userButtonPack">
        @*<a href="#"><div class="userBtnDescription" id="">Управление<br /> Предметами</div><img id="sbjd" src="~/image/icons/textbooks.png" alt="Управление Предметами" /></a>
            <a href="#"><div id="">Управление<br /> Учениками</div><img id="ppld" src="~/image/icons/pupil.png" alt="Управление Учениками" /></a>
            <a href="#"><div id="">Управление<br /> Родителями</div><img id="prtd" src="~/image/icons/parent_icon.png" alt="Управление Родителями" /></a>
            <a href="#"><div id="">Управление<br /> Учителями</div><img id="tcrd" src="~/image/icons/teacher.png" alt="Управление учителями школы" /></a>
            <a href="#"><div id="">Управление<br /> Менеджером</div><img id="mnrd" src="~/image/icons/Manager-512.png" alt="Управление менеджером школы" /></a>*@
        <a href="#"><div class="userBtnDescription" id="">Управление<br /> Группами</div><img id="tmtbl" src="~/image/icons/timeTableEdit.png" alt="Управление Группами" /></a>
        <a href="@Url.Action("Index")"><div class="userBtnDescription" id="">Управление<br /> Группами</div><img id="grpd" src="~/image/icons/group.png" alt="Управление Группами" /></a>
    </div>
</div>
<div class="parentControlPack">

</div>
<input type="date" name="ddate" value=""/>
<div id="adminContent">

</div>

